-- make profiles-id generated by Supabase's authentication subsystem
-- changes required:
-- 1 - drop DEFAULT from profiles.id since it's not self-minting them anymore
-- 2 - add FK constraint to point to auth.users(id)
alter table profiles
  alter column id drop default,
  add constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade;

create schema if not exists private;

-- `authenticated` must be able to REFERENCE objects in `private` so the RLS
-- helpers (invoked in the caller's context, e.g. admin_university_ids) resolve.
-- `private` is NOT in PostgREST's exposed schemas, so nothing here gets a REST
-- endpoint regardless of this grant.
grant usage on schema private to authenticated;

create function private.handle_new_user ()
  returns trigger
  security definer
  set search_path = ''
  as $$
begin
  insert into public.profiles (id, first_name, last_name)
    values (new.id, new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name');
  return NEW;
end;
$$
language plpgsql;

create trigger on_auth_user_created
  after insert on auth.users for each row
  execute function private.handle_new_user ();

